// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAIYxhX46WmqK7Ya1t_Taq6XsTbtiOoQdY',
    appId: '1:1050031393449:web:012625774b871c758737b8',
    messagingSenderId: '1050031393449',
    projectId: 'quizapp-4451e',
    authDomain: 'quizapp-4451e.firebaseapp.com',
    storageBucket: 'quizapp-4451e.appspot.com',
    measurementId: 'G-JP6P896FB1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDJK1707P9kSrFzaQLWkkpFRVThwccUvQ0',
    appId: '1:1050031393449:android:be017b40415b60b28737b8',
    messagingSenderId: '1050031393449',
    projectId: 'quizapp-4451e',
    storageBucket: 'quizapp-4451e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCv2Lv7fXO-7NbwmvqHMDcdqRA_UtKkkIc',
    appId: '1:1050031393449:ios:dca7ddad75835eab8737b8',
    messagingSenderId: '1050031393449',
    projectId: 'quizapp-4451e',
    storageBucket: 'quizapp-4451e.appspot.com',
    iosClientId: '1050031393449-rdta4i1k0v54sgnggut6b6duhmod6u8r.apps.googleusercontent.com',
    iosBundleId: 'com.example.quizApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCv2Lv7fXO-7NbwmvqHMDcdqRA_UtKkkIc',
    appId: '1:1050031393449:ios:dca7ddad75835eab8737b8',
    messagingSenderId: '1050031393449',
    projectId: 'quizapp-4451e',
    storageBucket: 'quizapp-4451e.appspot.com',
    iosClientId: '1050031393449-rdta4i1k0v54sgnggut6b6duhmod6u8r.apps.googleusercontent.com',
    iosBundleId: 'com.example.quizApp',
  );
}
